
development: &common_settings
  adapter: postgresql
  encoding: unicode
  database: vinti_development
  user: phai
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: vinti_test
  user: phai
  pool: 5

production: << *common_settings

